### PR TITLE
Use page titles instead of path

### PR DESCRIPTION
**Pull request by pamtbaau**

### CODE REVIEW

**Comment by pamtbaau** [comment]
I had to create a fix for the Admin urls for config files of plugins. Do you foresee other files to be included in Git which also might have different url logic? Thinking of data, accounts, theme config, ...

**Comment by hughbris** [comment]
It hadn't even occurred to me that there could be other useful links apart from pages. Good thinking. Maybe stuff in `env`?? Languages? I don't know Admin that well.

But .. when we get into more technical changes under `user`, I think it's unlikely to be edited via an Admin user who doesn't know Git.

**Comment by hughbris** [comment]
General review: this is a fantastic addition :)

I wanted to make these changes rather than requesting them, but I had another problem with NPM building the first one. I will describe the changes first:

* modules shouldn't be hyperlinked - not sure how they should be displayed though
* edit links should open in same window (IMO)
* I wonder if it's better to not hyperlink titles to make them easier to select (contradicting my earlier suggestion)

When I tried running `my-npm run build`, this was my output:

```sh

> pushy@1.0.0 build
> npm-run-all --parallel css js

sh: line 1: npm-run-all: command not found
```
I tried aliasing `my-npm` to `npm` in case NPM was invoking itself. I assume I need to establish aliases for `npm-run-all` and maybe other wrappers.

**Comment by pamtbaau** [comment]
> Maybe stuff in env??

AFAIK, it's the server that decides to write/retrieve the config file into/from the proper `env` folder. Admin just shows a config which makes it transparent to the user.

> modules shouldn't be hyperlinked - not sure how they should be displayed though

Modules can't be displayed separately. But maybe displaying the modular with an inline anchor in the url, like `http://modular-dev/#features`. This will scroll the modular to the module.

This might be difficult to achieve, since the server doesn't know which inline anchor will be defined for each module. Unless we can assume the creation of the inline anchor is always the same like `{{ module.menu|hyphenize }}`.

> edit links should open in same window (IMO)

OK, I'll change the behaviour for the edit links.

> I wonder if it's better to not hyperlink titles to make them easier to select (contradicting my earlier suggestion)

How does the user use it?
- Does the user always first lookup the page before selecting it?
- Or does the user most often just select and submit?
- ...

> I had another problem with NPM building

Have you run `$ npm install`?

**Comment by pamtbaau** [comment]
> modules shouldn't be hyperlinked - not sure how they should be displayed though

I assume that most, if not all, themes use `{{ module.menu|hyphenize }}` to create an anchor for the module. I've added functionality to get the Url of the Modular and append the anchor for the Module, like `https://domain/modular/#module`.

This will scroll the page to the current module when Author wishes to preview the module.

**Comment by hughbris** [comment]
> Have you run `$ npm install`?

No and thanks, that worked. These are just arbitrary magic incantations to me. `install` sounds like something you only do the first time.

> I assume that most, if not all, themes use `{{ module.menu|hyphenize }}` to create an anchor for the module.

That's a good intention but I don't think I've ever noticed a theme do this. Given that modules could be used for columns, footers (?), modals, I'm not sure the practice is reliably user friendly.

I am tempted to just merge this PR and continue the debate in issues. It depends whether this is stopping you progressing anything else. I am not actively building anything now because I'm too busy.

The page module handling is the only part of this PR I don't like. What if we just add "(module)" to the title and don't link it? I don't know.

**Comment by pamtbaau** [comment]
> No and thanks, that worked. These are just arbitrary magic incantations to me. install sounds like something you only do the first time.

And this is what you get in folder /node_modules: See video [npm install](https://www.reddit.com/r/ProgrammerHumor/comments/usjmcx/dont_try_this_at_home/)

> That's a good intention but I don't think I've ever noticed a theme do this. 

Just did a search on https://github.com/getgrav, only the Quark theme returned a hit... :-)
Do you want me to revert the last commit to remove the module link? I could postfix `(module)` to the title.

> I am not actively building anything now because I'm too busy.

Good to know. I was getting a deja-vue...

**Comment by hughbris** [comment]
Ha! Yep let's annotate "(module)" for now and be done with this.

**Comment by pamtbaau** [comment]
Git items will be displayed as follows:

| type |  shown as | external Url | editable in Admin |
|-------|:----------:|:--------:|:--------------:|
|page|  Title |yes        |yes|
|modular|Title| yes|yes|
|module|Title (module) |no|yes|
| config|path|no|yes|
|image|path|yes|no|
|other|?|?|?|

**Pull request merged**
