### PR TITLE
Fix banner + refresh changed item list

### PR DESCRIPTION
**Pull request by pamtbaau**
Issue of banner and non-refreshing page list should be fixed now.

Cause:
- Each commit made the code to fetch a new list. When no rows were fetched the "Nothing to publish" message overrides the Success message instantly.
- When painting the list of pages, the &lt;tbody> wasn't cleared.

Solution:
- Code does no longer show a banner message when there are no changes to publish.
- Cleared table body before displaying fresh list.

Todo:
- The empty table looks a bit ugly now. Not an ideal UX.
- Table header could use a bit of styling.
- I see you are not using the optional `notes` fields which provided the user to add a longer note. This is similar to Github's "Message"  and "Description" fields. If there is no use for the longer description, It might be better to remove it.

### CODE REVIEW

**Comment by hughbris** [comment]
Thanks :+1:

**Comment by hughbris** [comment]
Sorry just noticed your PR comments (testing this on a nearly launched site is getting confusing!)

> "Nothing to publish" message

I think ideally there will be two messages, one to say the action succeeded and another to reflect the current status. Low priority issue perhaps.

> I see you are not using the optional notes fields which provided the user to add a longer note. This is similar to Github's "Message" and "Description" fields. If there is no use for the longer description, It might be better to remove it.

Yes please, unless you can think of somewhere to store it *and* a reason.

> The empty table looks a bit ugly now. Not an ideal UX.

We'll get there.

**Comment by pamtbaau** [comment]
About the "description" field...

Git's commit message can be made up by two parts: A single line summary and a multiline description. These two parts need to be separated with a blank line.

Not knowing the requirements of the user, I've added the option to enter a commit description anyway. On the server, the two fields can be concatenated into a single commit message.

If it is useless to the client, I'll remove it.

**Comment by hughbris** [comment]
This sounds like it could be useful. I couldn't see that in [the manual](https://git-scm.com/docs/git-commit), do you mean Github?

Even if it's not part of git, I like the idea of forcing a headline and appending any longer details.

My clients have no specific requirements and I want this to be useful to any content editor. As usual, users prefer quick and simple.

I think for now, either leave it in and use it or comment it out while we consider it.

**Comment by pamtbaau** [comment]
See section [Discussion ](https://git-scm.com/docs/git-commit#_discussion)on the same manual page:

> Though not required, it’s a good idea to begin the commit message with a single short (less than 50 character) line summarizing the change, followed by a blank line and then a more thorough description. The text up to the first blank line in a commit message is treated as the commit title, and that title is used throughout Git. For example, [git-format-patch[1]](https://git-scm.com/docs/git-format-patch) turns a commit into email, and it uses the title on the Subject line and the rest of the commit in the body.

If you prefer to keep the longer description option for the user, the two fields should be concatenated (with an extra newline) either in JS when submitting the form, or on the server when receiving the form.

**Pull request merged**
